package org.gemalto.com.uaf;

/**
 * Created by jpaert on 9/6/2017.
 */
public enum UafServerStatus {
    SUCCESS("SUCCESS"),

    //Reg
    VALID("VALID"),
    INVALID_USERNAME("INVALID_USERNAME"),
    NOT_VERIFIED("NOT_VERIFIED"),
    FAILED_VALIDATION_ATTEMPT("FAILED_VALIDATION_ATTEMPT"),
    ASSERTIONS_CHECK_FAILED("ASSERTIONS_CHECK_FAILED"),

    //Auth
    FAILED_SIGNATURE_VERIFICATION("FAILED_SIGNATURE_VERIFICATION"),
    FAILED_SIGNATURE_NOT_VALID("FAILED_SIGNATURE_NOT_VALID"),
    FAILED_ASSERTION_VERIFICATION("FAILED_ASSERTION_VERIFICATION"),
    FAILED_TRANSACTION_HASH_VERIFICATION("FAILED_TRANSACTION_HASH_VERIFICATION"),
    AUTHENTICATORS_NOT_FOUND("AUTHENTICATORS_NOT_FOUND"),

    //From exception codes
    //FIXME: Will not be returned by the server as it looks up status in resource file
    INVALID_SERVER_DATA_EXPIRED("INVALID_SERVER_DATA_EXPIRED"),
    INVALID_SERVER_DATA_SIGNATURE_NO_MATCH("INVALID_SERVER_DATA_SIGNATURE_NO_MATCH"),
    INVALID_SERVER_DATA_CHECK_FAILED("INVALID_SERVER_DATA_CHECK_FAILED"),
    UNACCEPTABLE_CONTENT("UNACCEPTABLE_CONTENT");

    private final String label;

    UafServerStatus(final String label) {
        this.label = label;
    }

    public String getLabel() {
        return this.label;
    }

}